<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.2.0</Version>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
    <InformationalVersion>v0.2-test-m1</InformationalVersion>
    <Product>OTMR CCF Editor / Creator</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CcfEditor.Core\CcfEditor.Core.csproj" />
    <ProjectReference Include="..\CcfEditor.Otmr\CcfEditor.Otmr.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="OtmrLiveControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="OtmrLiveControl.Designer.cs">
      <DependentUpon>OtmrLiveControl.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="MainForm.resx">
      <DependentUpon>MainForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="OtmrLiveControl.resx">
      <DependentUpon>OtmrLiveControl.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
