#nullable enable

namespace CcfEditor.WinForms;

partial class OtmrServerSyncControl
{
    private System.ComponentModel.IContainer? components = null;
    private TableLayoutPanel rootLayout = null!;
    private GroupBox connectionGroupBox = null!;
    private TableLayoutPanel connectionLayout = null!;
    private Label syncServerUrlLabel = null!;
    private TextBox syncServerUrlTextBox = null!;
    private Label syncApiTokenLabel = null!;
    private TextBox syncApiTokenTextBox = null!;
    private CheckBox syncEnabledCheckBox = null!;
    private CheckBox syncAllowHttpTestServerCheckBox = null!;
    private FlowLayoutPanel settingsButtonsPanel = null!;
    private Button saveSyncSettingsButton = null!;
    private Button testServerButton = null!;
    private Label connectionNoticeLabel = null!;
    private GroupBox uploadStatusGroupBox = null!;
    private TableLayoutPanel uploadStatusLayout = null!;
    private Label syncPendingCountLabel = null!;
    private Label syncCurrentStateLabel = null!;
    private Label syncLastAttemptLabel = null!;
    private Label syncLastResultLabel = null!;
    private Label syncLastErrorLabel = null!;
    private Button syncPendingRecordingsButton = null!;
    private Label localEvidenceNoticeLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components is not null)
            components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayout = new TableLayoutPanel();
        connectionGroupBox = new GroupBox();
        connectionLayout = new TableLayoutPanel();
        syncServerUrlLabel = new Label();
        syncServerUrlTextBox = new TextBox();
        syncApiTokenLabel = new Label();
        syncApiTokenTextBox = new TextBox();
        syncEnabledCheckBox = new CheckBox();
        syncAllowHttpTestServerCheckBox = new CheckBox();
        settingsButtonsPanel = new FlowLayoutPanel();
        saveSyncSettingsButton = new Button();
        testServerButton = new Button();
        connectionNoticeLabel = new Label();
        uploadStatusGroupBox = new GroupBox();
        uploadStatusLayout = new TableLayoutPanel();
        syncPendingCountLabel = new Label();
        syncCurrentStateLabel = new Label();
        syncLastAttemptLabel = new Label();
        syncLastResultLabel = new Label();
        syncLastErrorLabel = new Label();
        syncPendingRecordingsButton = new Button();
        localEvidenceNoticeLabel = new Label();
        rootLayout.SuspendLayout();
        connectionGroupBox.SuspendLayout();
        connectionLayout.SuspendLayout();
        settingsButtonsPanel.SuspendLayout();
        uploadStatusGroupBox.SuspendLayout();
        uploadStatusLayout.SuspendLayout();
        SuspendLayout();

        rootLayout.AutoScroll = true;
        rootLayout.ColumnCount = 1;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.Controls.Add(connectionGroupBox, 0, 0);
        rootLayout.Controls.Add(uploadStatusGroupBox, 0, 1);
        rootLayout.Controls.Add(localEvidenceNoticeLabel, 0, 2);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Name = "serverSyncRootLayout";
        rootLayout.Padding = new Padding(16);
        rootLayout.RowCount = 3;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 230F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 280F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        connectionGroupBox.Controls.Add(connectionLayout);
        connectionGroupBox.Dock = DockStyle.Fill;
        connectionGroupBox.Name = "serverConnectionGroupBox";
        connectionGroupBox.Padding = new Padding(12);
        connectionGroupBox.Text = "SERVER CONNECTION";

        connectionLayout.ColumnCount = 4;
        connectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 105F));
        connectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55F));
        connectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 135F));
        connectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F));
        connectionLayout.Controls.Add(syncServerUrlLabel, 0, 0);
        connectionLayout.Controls.Add(syncServerUrlTextBox, 1, 0);
        connectionLayout.SetColumnSpan(syncServerUrlTextBox, 3);
        connectionLayout.Controls.Add(syncApiTokenLabel, 0, 1);
        connectionLayout.Controls.Add(syncApiTokenTextBox, 1, 1);
        connectionLayout.SetColumnSpan(syncApiTokenTextBox, 3);
        connectionLayout.Controls.Add(syncEnabledCheckBox, 1, 2);
        connectionLayout.Controls.Add(syncAllowHttpTestServerCheckBox, 2, 2);
        connectionLayout.SetColumnSpan(syncAllowHttpTestServerCheckBox, 2);
        connectionLayout.Controls.Add(settingsButtonsPanel, 1, 3);
        connectionLayout.SetColumnSpan(settingsButtonsPanel, 3);
        connectionLayout.Controls.Add(connectionNoticeLabel, 0, 4);
        connectionLayout.SetColumnSpan(connectionNoticeLabel, 4);
        connectionLayout.Dock = DockStyle.Fill;
        connectionLayout.Name = "serverConnectionLayout";
        connectionLayout.RowCount = 5;
        connectionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        connectionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        connectionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        connectionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        connectionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        syncServerUrlLabel.Dock = DockStyle.Fill;
        syncServerUrlLabel.Name = "syncServerUrlLabel";
        syncServerUrlLabel.Text = "Server URL:";
        syncServerUrlLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncServerUrlTextBox.Dock = DockStyle.Fill;
        syncServerUrlTextBox.Name = "syncServerUrlTextBox";
        syncApiTokenLabel.Dock = DockStyle.Fill;
        syncApiTokenLabel.Name = "syncApiTokenLabel";
        syncApiTokenLabel.Text = "API Token:";
        syncApiTokenLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncApiTokenTextBox.Dock = DockStyle.Fill;
        syncApiTokenTextBox.Name = "syncApiTokenTextBox";
        syncApiTokenTextBox.PlaceholderText = "Enter token to save";
        syncApiTokenTextBox.UseSystemPasswordChar = true;
        syncEnabledCheckBox.AutoSize = true;
        syncEnabledCheckBox.Dock = DockStyle.Fill;
        syncEnabledCheckBox.Name = "syncEnabledCheckBox";
        syncEnabledCheckBox.Text = "Sync Enabled";
        syncEnabledCheckBox.CheckedChanged += SyncEnabledCheckBox_CheckedChanged;
        syncAllowHttpTestServerCheckBox.AutoSize = true;
        syncAllowHttpTestServerCheckBox.Dock = DockStyle.Fill;
        syncAllowHttpTestServerCheckBox.Name = "syncAllowHttpTestServerCheckBox";
        syncAllowHttpTestServerCheckBox.Text = "TEST ONLY: allow HTTP to exact test server";
        settingsButtonsPanel.Controls.Add(saveSyncSettingsButton);
        settingsButtonsPanel.Controls.Add(testServerButton);
        settingsButtonsPanel.Dock = DockStyle.Fill;
        settingsButtonsPanel.Name = "syncSettingsButtonsPanel";
        settingsButtonsPanel.WrapContents = false;
        saveSyncSettingsButton.AutoSize = true;
        saveSyncSettingsButton.Name = "saveSyncSettingsButton";
        saveSyncSettingsButton.Text = "SAVE SETTINGS";
        saveSyncSettingsButton.Click += SaveSyncSettingsButton_Click;
        testServerButton.AutoSize = true;
        testServerButton.Name = "testServerButton";
        testServerButton.Text = "TEST SERVER";
        testServerButton.Click += TestServerButton_Click;
        connectionNoticeLabel.Dock = DockStyle.Fill;
        connectionNoticeLabel.ForeColor = Color.DimGray;
        connectionNoticeLabel.Name = "connectionNoticeLabel";
        connectionNoticeLabel.Text = "No automatic/background synchronization. TEST SERVER is anonymous /health; uploads use the securely stored bearer token.";
        connectionNoticeLabel.TextAlign = ContentAlignment.MiddleLeft;

        uploadStatusGroupBox.Controls.Add(uploadStatusLayout);
        uploadStatusGroupBox.Dock = DockStyle.Fill;
        uploadStatusGroupBox.Name = "uploadStatusGroupBox";
        uploadStatusGroupBox.Padding = new Padding(12);
        uploadStatusGroupBox.Text = "UPLOAD STATUS";
        uploadStatusLayout.ColumnCount = 2;
        uploadStatusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        uploadStatusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        uploadStatusLayout.Controls.Add(syncPendingCountLabel, 0, 0);
        uploadStatusLayout.Controls.Add(syncCurrentStateLabel, 1, 0);
        uploadStatusLayout.Controls.Add(syncLastAttemptLabel, 0, 1);
        uploadStatusLayout.SetColumnSpan(syncLastAttemptLabel, 2);
        uploadStatusLayout.Controls.Add(syncLastResultLabel, 0, 2);
        uploadStatusLayout.SetColumnSpan(syncLastResultLabel, 2);
        uploadStatusLayout.Controls.Add(syncLastErrorLabel, 0, 3);
        uploadStatusLayout.SetColumnSpan(syncLastErrorLabel, 2);
        uploadStatusLayout.Controls.Add(syncPendingRecordingsButton, 0, 4);
        uploadStatusLayout.SetColumnSpan(syncPendingRecordingsButton, 2);
        uploadStatusLayout.Dock = DockStyle.Fill;
        uploadStatusLayout.Name = "uploadStatusLayout";
        uploadStatusLayout.RowCount = 5;
        uploadStatusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        uploadStatusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        uploadStatusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        uploadStatusLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        uploadStatusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        syncPendingCountLabel.Dock = DockStyle.Fill;
        syncPendingCountLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        syncPendingCountLabel.Name = "syncPendingCountLabel";
        syncPendingCountLabel.Text = "Pending recordings: 0";
        syncPendingCountLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncCurrentStateLabel.Dock = DockStyle.Fill;
        syncCurrentStateLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        syncCurrentStateLabel.Name = "syncCurrentStateLabel";
        syncCurrentStateLabel.Text = "Current: -";
        syncCurrentStateLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncLastAttemptLabel.AutoEllipsis = true;
        syncLastAttemptLabel.Dock = DockStyle.Fill;
        syncLastAttemptLabel.Name = "syncLastAttemptLabel";
        syncLastAttemptLabel.Text = "Last attempt: Never";
        syncLastAttemptLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncLastResultLabel.AutoEllipsis = true;
        syncLastResultLabel.Dock = DockStyle.Fill;
        syncLastResultLabel.Name = "syncLastResultLabel";
        syncLastResultLabel.Text = "Last result: Not attempted";
        syncLastResultLabel.TextAlign = ContentAlignment.MiddleLeft;
        syncLastErrorLabel.AutoEllipsis = true;
        syncLastErrorLabel.Dock = DockStyle.Fill;
        syncLastErrorLabel.ForeColor = Color.DarkRed;
        syncLastErrorLabel.Name = "syncLastErrorLabel";
        syncLastErrorLabel.Text = "Last error: -";
        syncLastErrorLabel.TextAlign = ContentAlignment.TopLeft;
        syncPendingRecordingsButton.Anchor = AnchorStyles.Left;
        syncPendingRecordingsButton.AutoSize = true;
        syncPendingRecordingsButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        syncPendingRecordingsButton.Name = "syncPendingRecordingsButton";
        syncPendingRecordingsButton.Text = "SYNC PENDING RECORDINGS";
        syncPendingRecordingsButton.Click += SyncPendingRecordingsButton_Click;

        localEvidenceNoticeLabel.Dock = DockStyle.Top;
        localEvidenceNoticeLabel.ForeColor = Color.DimGray;
        localEvidenceNoticeLabel.Name = "localEvidenceNoticeLabel";
        localEvidenceNoticeLabel.Padding = new Padding(8);
        localEvidenceNoticeLabel.Text = "Uploads are atomic and manual. Successful upload never deletes or alters the complete local SQLite recording.";
        localEvidenceNoticeLabel.TextAlign = ContentAlignment.TopLeft;

        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        Controls.Add(rootLayout);
        Name = "OtmrServerSyncControl";
        Size = new Size(1200, 700);
        uploadStatusLayout.ResumeLayout(true);
        uploadStatusLayout.PerformLayout();
        uploadStatusGroupBox.ResumeLayout(true);
        settingsButtonsPanel.ResumeLayout(true);
        settingsButtonsPanel.PerformLayout();
        connectionLayout.ResumeLayout(true);
        connectionLayout.PerformLayout();
        connectionGroupBox.ResumeLayout(true);
        rootLayout.ResumeLayout(true);
        ResumeLayout(true);
    }
}
